#!/bin/bash

display_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain" | awk '{print $1}')
        if [ -n "$result" ]; then
            record_type=$(dig +short "$sub.$domain" | awk 'NR==1 {print $NF}')
            echo "The subdomain $sub is a $record_type record and points to $result"
        fi
    done
}

if [ $# -eq 1 ]; then
    display_info "$1"
elif [ $# -eq 2 ]; then
    display_info "$1" "$2"
else
    echo "Invalid number of arguments. Usage: $0 domain [subdomain]"
    exit 1
fi
