#!/usr/bin/env bash
# Script to display information about subdomains

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    
    for sub in "${subdomains[@]}"; do
        dig_output=$(dig "$sub"."$domain" | awk '/ANSWER SECTION/ {p=1; next} p {print}' | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
        record_type=$(echo "$dig_output" | awk 'NR==1{print $2}')
        destination=$(echo "$dig_output" | awk 'NR==1{print $1}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

get_subdomain_info "$1" "$2"
