#!/usr/bin/env bash
# Configure Nginx to include a custom header in HTTP response on web-01 and web-02

# Set the custom header value
custom_header="X-Served-By $(hostname)"

# Function to configure Nginx
configure_nginx() {
    echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html > /dev/null
    sudo mkdir -p /var/www/html
    echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

    # Add the custom header to Nginx configuration
    sudo sed -i -E "s/# server_name _;/server_name _;\n    add_header $1;/" /etc/nginx/sites-available/default

    # Restart Nginx service
    sudo systemctl restart nginx
}

# Execute the function on web-01 and web-02 servers
configure_nginx "$custom_header"
