#!/usr/bin/env bash

# Installs, configures, and starts the load balancer
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# The load balancer's configuration
DOMAIN_NAME='beta-scribbles.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG="
#--${DOMAIN_NAME}-params-begin--
backend ${DOMAIN_NAME}-backend
    balance roundrobin
    server 402441-web-01 3.84.255.39:80 check
    server 402441-web-02 54.160.72.183:80 check

frontend ${DOMAIN_NAME}-frontend
    bind *:80
    mode http
    default_backend ${DOMAIN_NAME}-backend
#--${DOMAIN_NAME}-params-end--
"

# Ensure the existence of required files
sudo touch "$INIT_FILE"
sudo touch "$CONFIG_FILE"

CONFIG_WORDS=$(grep -c "$DOMAIN_NAME-backend" "$CONFIG_FILE")

if [ $(grep -c '^ENABLED=[01]$' "$INIT_FILE") -gt 0 ]; then
    sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
    echo 'ENABLED=1' | sudo tee -a "$INIT_FILE"
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
    echo -e "$HAPROXY_LB_CONFIG" | sudo tee -a "$CONFIG_FILE"
else
    start_tkn="#--${DOMAIN_NAME}-params-begin--"
    end_tkn="#--${DOMAIN_NAME}-params-end--"
    a=$(grep -n "$start_tkn" "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -n "$end_tkn" "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sudo sed -i "$a,$b d" "$CONFIG_FILE"
    echo -en "$HAPROXY_LB_CONFIG" | sudo tee -a "$CONFIG_FILE"
fi

if ! pgrep haproxy >/dev/null; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
