#!/bin/bash
# Installs, configures, and starts the load balancer
STUDENT_ID="402441"

# Update package list and install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 ${STUDENT_ID}-web-01:80 
    server web-02 ${STUDENT_ID}-web-02:80 
EOF

# Enable HAProxy service
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Verify HAProxy status
sudo systemctl status haproxy
